name: Build and deploy Node.js app to Azure Web App - porto-api

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      APP_KEY: ${{ secrets.APP_KEY }}
      HOST: ${{ secrets.HOST }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      # Add any additional environment variables here

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Create .env file
        run: |
          echo NODE_ENV=${{ env.NODE_ENV }} >> .env
          echo APP_KEY=${{ env.APP_KEY }} >> .env
          echo HOST=${{ env.HOST }} >> .env
          echo LOG_LEVEL=${{ env.LOG_LEVEL }} >> .env
          echo DB_HOST=${{ env.DB_HOST }} >> .env
          echo DB_PORT=${{ env.DB_PORT }} >> .env
          echo DB_USER=${{ env.DB_USER }} >> .env
          echo DB_PASSWORD=${{ env.DB_PASSWORD }} >> .env
          echo DB_DATABASE=${{ env.DB_DATABASE }} >> .env

      - name: Install dependencies
        run: npm install
        
      - name: Build the project
        run: npm run build --if-present

      - name: Run tests
        run: npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C7BF3CBBA59846E99CBCEC488EA98F5B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B826B8D5DBFE429893D4C0DB82F5FF07 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_123CA132CDC24C6E85FF1D4944F0AF2A }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'porto-api'
          slot-name: 'Production'
          package: .
